// generated by GitHub Copilot
function formatData() {
    const inputData = document.getElementById('inputData').value;
    const lines = inputData.trim().split('\n');
    const columns = lines.map(line => line.split('|').map(cell => cell.trim()));

    // Calculate the maximum width of each column
    const numColumns = columns[0].length;
    const maxWidths = Array(numColumns).fill(0);
    columns.forEach(row => {
        row.forEach((cell, i) => {
            maxWidths[i] = Math.max(maxWidths[i], cell.length);
        });
    });

    // Format each row
    const formattedLines = columns.map(row => {
        return row.map((cell, i) => cell.padEnd(maxWidths[i])).join(' | ');
    });

    // Join the formatted lines into a single string
    const formattedData = formattedLines.join('\n');
    document.getElementById('outputData').value = formattedData;
}

function changeFontSize(delta) {
    const textareas = document.querySelectorAll('textarea');
    textareas.forEach(textarea => {
        const currentSize = parseFloat(window.getComputedStyle(textarea, null).getPropertyValue('font-size'));
        textarea.style.fontSize = (currentSize + delta) + 'px';
    });
}

function clearTextAreas() {
    document.getElementById('inputData').value = '';
    document.getElementById('outputData').value = '';
}